//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int ID { get; set; }
        public int ID_EQUIPO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ASUNTO { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
