//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int ID { get; set; }
        public string ZONA { get; set; }
        public string CODIGO_INT { get; set; }
        public string CODIGO_ADM { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<byte> CANTIDAD { get; set; }
        public Nullable<byte> UNIDAD { get; set; }
    }
}
