//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lubricacion
    {
        public int ID { get; set; }
        public int ID_EQUIPO { get; set; }
        public string PTOS_LUB { get; set; }
        public string LUBRICANTE { get; set; }
        public string TIPO { get; set; }
        public Nullable<byte> PTO { get; set; }
        public string CANTIDAD { get; set; }
        public Nullable<byte> TIEMPO { get; set; }
        public Nullable<byte> UNIDAD_TIEMPO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<bool> PRINCIPAL { get; set; }
    }
}
